### PR TITLE
these scripts use bash constructs and so should use /bin/bash

### PR DESCRIPTION
**Pull request by garthy**

### CODE REVIEW

**Comment by e-nikolov** [comment]
I don't think alpine has bash installed. If you replace #!/bin/sh with #!/bin/bash, the build.sh and test.sh scripts won't be able to run inside an alpine container.

**Comment by thockin** [comment]
Alpine aliases sh to ash - this could explicitly call out `ash` instead ?

**Comment by sevein** [comment]
The problem is that `ash` isn't installed by default in debian-based images like `golang:1.9`.

Should we try to tweak the scripts so they're portable?

**Comment by thockin** [comment]
As long as it doesn't cripple the scripts, I am ok with that.  But this
whole project was designed to run in Alpine - why does it matter if they
don't run on debian?  Why would one use the non-alpine version?

**Pull request closed without merging**
