### PR TITLE
Update `tools/` dependencies

### PR DESCRIPTION
**Pull request by jingyuanliang**

### CODE REVIEW

**Comment by thockin** [comment]
Is there a bug or something driving the need for all of these to update?

**Comment by jingyuanliang** [comment]
For containerd v1.6.12 => v1.6.18. The others don't *have* to be updated though.

https://pkg.go.dev/github.com/containerd/containerd?tab=versions

**Comment by thockin** [comment]
Sorry, I just merged from dependabot, which caused a conflict.  I am fine with "opportunistic update" as an answer, just wanted to understand

**Comment by thockin** [comment]
Applied manually

**Pull request closed without merging**
