### PR TITLE
Specify source build location before globbing

### PR DESCRIPTION
**Pull request by GrantSeltzer**
[Prior to to the soon to be released go 1.9](https://github.com/golang/go/issues/19090), the `...` file glob symbol does not exclude the vendor directory. By not specifying `cmd` the build script will attempt to build vendor. 

By adding cmd to the install line, only build-able packages will be touched by `build.sh`

Signed-off-by: grantseltzer <grant@capsule8.com>

### CODE REVIEW

**Comment by GrantSeltzer** [comment]
@thockin Any feedback on this?

**Comment by thockin** [comment]
Sorry, it turns out I have to "watch" my own repos, or I never get notifications of stuff like this.  Looking now.

**Comment by thockin** [comment]
With this change, none of the .a files in any directory get "installed" which will cause serious build slowdowns as those get relinked on subsequent builds.

What is the problem caused by building vendor?

**Comment by GrantSeltzer** [comment]
Ah, yea those should be included. Got to fix this to only exclude vendor.

The issue with building vendor is that it's unnecessary. Without this change `go build` will look for build-able sources in vendor and actually do so. 

I believe this often goes unnoticed. The way I realized is that dep was pulling in all necessary dependencies for what is actually supposed to be built but then this line in `build.sh` was saying I was missing stuff.

**Pull request closed without merging**
